version: 2
updates:

  # Maintain dependencies for GitHub Actions
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: daily

- package-ecosystem: pip-compile
  directory: /
  schedule:
    interval: daily

- package-ecosystem: pip
  directory: /
  schedule:
    interval: weekly

- package-ecosystem: npm
  directory: /webui
  schedule:
    interval: weekly
