name: Bug report
description: Report something that is not working as expected.
title: 'bug: <summary>'
labels: [bug, needs triage]
body:
- type: markdown
  attributes:
    value: |
      Thank you for helping us improve qBitrr. Please fill in every required field so we can reproduce and fix the problem quickly. Attach relevant log snippets and mask any sensitive information.
- type: textarea
  id: summary
  attributes:
    label: Issue summary
    description: What is happening? Provide a concise, one paragraph overview.
    placeholder: Downloads stay in Stalled state even after rechecking
  validations:
    required: true
- type: textarea
  id: repro
  attributes:
    label: Steps to reproduce
    description: List the exact steps (including config tweaks) needed to reproduce the issue.
    placeholder: |-
      1. Set ...
      2. Start ...
      3. Observe ...
  validations:
    required: true
- type: textarea
  id: expected
  attributes:
    label: Expected behaviour
    description: What did you expect to happen instead?
  validations:
    required: true
- type: textarea
  id: actual
  attributes:
    label: Actual behaviour and logs
    description: Paste relevant log excerpts (use triple backticks) and describe what you saw.
    render: shell
  validations:
    required: true
- type: input
  id: version
  attributes:
    label: qBitrr version
    description: Output of `qBitrr2 --version` or the Docker image tag.
    placeholder: 4.10.28 (docker:latest)
  validations:
    required: true
- type: input
  id: platform
  attributes:
    label: Environment
    description: Operating system and deployment details (native venv, Docker, etc.).
    placeholder: Ubuntu 22.04, Docker compose
  validations:
    required: true
- type: textarea
  id: integrations
  attributes:
    label: Integration versions
    description: Include qBittorrent, Radarr, Sonarr, Overseerr/Ombi versions and any other relevant services.
  validations:
    required: true
- type: checkboxes
  id: confirmations
  attributes:
    label: Pre-flight checklist
    options:
    - label: I searched existing issues and discussions.
      required: true
    - label: Logging is enabled and the attached logs cover the failure.
      required: true
- type: textarea
  id: extra
  attributes:
    label: Additional context
    description: Optional details, links, or screenshots.
  validations:
    required: false
