name: Autofix Failed Workflows

on:
  workflow_run:
    workflows:
    - CI
    types:
    - completed

jobs:
  codex-autofix:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      actions: read
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      GITHUB_TOKEN: ${{ secrets.PAT }}
      AUTOFIX_MODEL: ${{ vars.AUTOFIX_MODEL || 'gpt-4.1-mini' }}
      AUTOFIX_BASE_BRANCH: ${{ vars.AUTOFIX_BASE_BRANCH || '' }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install openai requests
    - name: Attempt automatic remediation
      run: |
        python .github/autofix/auto_fix.py --base "${AUTOFIX_BASE_BRANCH}"
