name: Nightly

on:
  push:
    branches:
    - master

defaults:
  run:
    shell: bash
env:
  project-name: qBitrr
  GREN_GITHUB_TOKEN: ${{ secrets.PAT }}

jobs:
  docker_image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    if: ${{ ! startsWith(github.event.head_commit.message, '[patch]') && ! startsWith(github.event.head_commit.message, '[minor]') && ! startsWith(github.event.head_commit.message, '[major]') }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: master
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Login to Container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.PAT }}
    - name: Build and push DockerHub
      env:
        DOCKER_BUILDKIT: 1
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64
        push: true
        tags: feramance/qbitrr:nightly
        cache-from: type=gha
        cache-to: type=gha,mode=max
    - name: Build and push Container registry
      env:
        DOCKER_BUILDKIT: 1
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64
        push: true
        tags: ghcr.io/${{ github.repository }}:nightly
        cache-from: type=gha
        cache-to: type=gha,mode=max
