name: Nightly

on:
  push:
    branches:
    - master
    paths-ignore:
    - '**.md'
    - .github/FUNDING.yml

defaults:
  run:
    shell: bash

env:
  project-name: qBitrr

jobs:
  docker_image:
    name: Build Docker Images
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    if: ${{ ! startsWith(github.event.head_commit.message, '[patch]') && ! startsWith(github.event.head_commit.message, '[minor]') && ! startsWith(github.event.head_commit.message, '[major]') }}
    strategy:
      matrix:
        platform: [amd64, arm64]
    steps:
    - id: string
      uses: ASzc/change-string-case-action@v6
      with:
        string: ${{ github.repository }}
    - name: Checkout
      uses: actions/checkout@v6
      with:
        fetch-depth: 0
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Login to Container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.REG_TOKEN }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          feramance/qbitrr
          ghcr.io/${{ steps.string.outputs.lowercase }}
        tags: |
          type=edge
    - name: Build and push Docker images
      env:
        DOCKER_BUILDKIT: 1
      uses: docker/build-push-action@v6
      with:
        context: .
        platforms: linux/amd64
        push: true
        tags: feramance/qbitrr:nightly,ghcr.io/${{ steps.string.outputs.lowercase }}:nightly
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
