name: Nightly v4

on:
  push:
    branches:
    - v4

defaults:
  run:
    shell: bash
env:
  project-name: qBitrr
  GREN_GITHUB_TOKEN: ${{ secrets.PAT }}

jobs:
  docker_image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      env:
        DOCKER_BUILDKIT: 1
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64
        push: true
        tags: feramance/qbitrr:nightlyv4
        cache-from: type=gha
        cache-to: type=gha,mode=max
